### ISSUE TITLE
The rule ||genuitec.com could be deleted

### ISSUE THREAD

**Issue by Firef0x** [Wllmw/GFWListPlus#3]
Since ||genuitec.com has been added to GFWList (See https://code.google.com/p/autoproxy-gfwlist/issues/detail?id=135 ), the rule in https://github.com/Wllmw/GFWListPlus/blob/master/gfwlistplus.txt#L32 from commit https://github.com/Wllmw/GFWListPlus/commit/5216b9a0589a01407ed9138576a57b91ee0ec1f0 could be deleted.

**Comment by Wllmw** [comment]
I'll update it later, thanks

**Comment by Firef0x** [comment]
#### Thx for your update! I would close this issue.
