### ISSUE TITLE
小方发布gfwlist-txt小方维护版(有几条他维护的内容，好像可以添加？)

### ISSUE THREAD

**Issue by laincat** [Wllmw/GFWListPlus#4]
http://ssh.xiaofang.me/gfw.txt

http://www.xiaofang.me/2013/05/16/%E5%B0%8F%E6%96%B9%E5%8F%91%E5%B8%83gfwlist-txt%E5%B0%8F%E6%96%B9%E7%BB%B4%E6%8A%A4%E7%89%88/

**Comment by Wllmw** [comment]
没发现需要添加的，上面列的几个用opendns都可以正常解析访问
